"""Report writer that generates Markdown, HTML, and PDF output.

Assembles a Report model into a professional Markdown document, converts to HTML
with styled CSS typography, and generates a PDF via WeasyPrint.
"""

from __future__ import annotations

import asyncio
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

import markdown2
import structlog

from app.config import get_settings
from app.models.citation import Reference
from app.models.report import Report, ReportConfig, ReportSection

logger = structlog.get_logger(__name__)


# ── Professional CSS ────────────────────────────────────────────────────────

_REPORT_CSS = """\
@page {
    size: A4;
    margin: 2.5cm 2cm 2.5cm 2cm;

    @top-center {
        content: string(report-title);
        font-size: 9pt;
        color: #666;
        font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
    }
    @bottom-center {
        content: counter(page);
        font-size: 9pt;
        color: #666;
        font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
    }
    @bottom-right {
        content: "Generated by Autonomous Research Agent";
        font-size: 7pt;
        color: #999;
        font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
    }
}

@page :first {
    @top-center { content: none; }
    @bottom-right { content: none; }
}

:root {
    --color-primary: #1a365d;
    --color-secondary: #2b6cb0;
    --color-text: #2d3748;
    --color-muted: #718096;
    --color-border: #e2e8f0;
    --color-bg-light: #f7fafc;
    --color-accent: #3182ce;
}

* {
    box-sizing: border-box;
}

body {
    font-family: "Georgia", "Times New Roman", serif;
    font-size: 11pt;
    line-height: 1.7;
    color: var(--color-text);
    max-width: 100%;
}

/* Title page */
.title-block {
    string-set: report-title content();
    text-align: center;
    padding: 4cm 0 2cm 0;
    page-break-after: always;
}

.title-block h1 {
    font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
    font-size: 26pt;
    font-weight: 700;
    color: var(--color-primary);
    margin-bottom: 0.5em;
    line-height: 1.2;
}

.title-block .subtitle {
    font-size: 13pt;
    color: var(--color-muted);
    margin-bottom: 2em;
    font-style: italic;
}

.title-block .meta {
    font-size: 10pt;
    color: var(--color-muted);
    border-top: 1px solid var(--color-border);
    padding-top: 1em;
    margin-top: 2em;
}

.title-block .meta span {
    display: block;
    margin: 0.3em 0;
}

/* Table of Contents */
.toc {
    page-break-after: always;
}

.toc h2 {
    font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
    font-size: 18pt;
    color: var(--color-primary);
    border-bottom: 2px solid var(--color-secondary);
    padding-bottom: 0.3em;
    margin-bottom: 1em;
}

.toc ul {
    list-style: none;
    padding-left: 0;
}

.toc li {
    padding: 0.4em 0;
    border-bottom: 1px dotted var(--color-border);
    font-size: 11pt;
}

.toc li a {
    color: var(--color-text);
    text-decoration: none;
}

/* Headings */
h1, h2, h3, h4, h5, h6 {
    font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
    color: var(--color-primary);
    margin-top: 1.5em;
    margin-bottom: 0.5em;
    line-height: 1.3;
}

h2 {
    font-size: 16pt;
    border-bottom: 2px solid var(--color-secondary);
    padding-bottom: 0.3em;
}

h3 {
    font-size: 13pt;
    color: var(--color-secondary);
}

h4 {
    font-size: 11pt;
    font-style: italic;
}

/* Paragraphs */
p {
    margin-bottom: 0.8em;
    text-align: justify;
    hyphens: auto;
}

/* Lists */
ul, ol {
    margin-bottom: 1em;
    padding-left: 1.5em;
}

li {
    margin-bottom: 0.3em;
}

/* Block quotes */
blockquote {
    border-left: 4px solid var(--color-accent);
    background: var(--color-bg-light);
    padding: 0.8em 1.2em;
    margin: 1em 0;
    font-style: italic;
    color: var(--color-muted);
}

/* Code */
code {
    font-family: "Menlo", "Consolas", "Monaco", monospace;
    font-size: 9pt;
    background: var(--color-bg-light);
    padding: 0.15em 0.4em;
    border-radius: 3px;
    border: 1px solid var(--color-border);
}

pre {
    background: #1a202c;
    color: #e2e8f0;
    padding: 1em;
    border-radius: 6px;
    overflow-x: auto;
    font-size: 9pt;
    line-height: 1.5;
    margin: 1em 0;
}

pre code {
    background: none;
    border: none;
    padding: 0;
    color: inherit;
}

/* Tables */
table {
    width: 100%;
    border-collapse: collapse;
    margin: 1.2em 0;
    font-size: 10pt;
}

th {
    background: var(--color-primary);
    color: white;
    font-weight: 600;
    padding: 0.6em 0.8em;
    text-align: left;
    font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
}

td {
    padding: 0.5em 0.8em;
    border-bottom: 1px solid var(--color-border);
}

tr:nth-child(even) td {
    background: var(--color-bg-light);
}

/* References section */
.references {
    font-size: 9.5pt;
    line-height: 1.6;
}

.references p {
    text-indent: -1.5em;
    padding-left: 1.5em;
    margin-bottom: 0.5em;
    text-align: left;
}

/* Horizontal rules */
hr {
    border: none;
    border-top: 1px solid var(--color-border);
    margin: 2em 0;
}

/* Links */
a {
    color: var(--color-accent);
    text-decoration: none;
}

a:hover {
    text-decoration: underline;
}

/* Strong / emphasis */
strong {
    color: var(--color-primary);
}

/* Summary box */
.executive-summary {
    background: var(--color-bg-light);
    border: 1px solid var(--color-border);
    border-left: 4px solid var(--color-accent);
    padding: 1.2em 1.5em;
    margin: 1.5em 0;
    border-radius: 0 6px 6px 0;
}

/* Report statistics footer */
.report-stats {
    font-size: 9pt;
    color: var(--color-muted);
    border-top: 1px solid var(--color-border);
    padding-top: 1em;
    margin-top: 3em;
}
"""


# ── ReportWriterTool ────────────────────────────────────────────────────────

class ReportWriterTool:
    """Generate professional research reports in Markdown, HTML, and PDF.

    Features
    --------
    - Assembles Markdown from a ``Report`` model with structured sections.
    - Generates a styled HTML document using ``markdown2``.
    - Produces a print-ready PDF via ``WeasyPrint`` with professional CSS
      (page numbers, headers, good typography).
    - All heavy I/O (file writing, PDF rendering) is offloaded to threads.

    Usage
    -----
    >>> writer = ReportWriterTool()
    >>> md = writer.generate_markdown(report)
    >>> paths = await writer.generate_all(report)
    >>> print(paths)  # {'markdown': '...', 'html': '...', 'pdf': '...'}
    """

    def __init__(self, output_dir: str | Path | None = None) -> None:
        settings = get_settings()
        self._output_dir = Path(output_dir) if output_dir else settings.reports_path
        self._log = logger.bind(tool="ReportWriterTool")

    # ── Public API ──────────────────────────────────────────────

    def generate_markdown(self, report: Report) -> str:
        """Assemble a complete Markdown document from a Report model.

        Parameters
        ----------
        report:
            The Report model containing sections, references, and config.

        Returns
        -------
        str
            Complete Markdown document.
        """
        self._log.info("markdown_generation_start", title=report.title)
        parts: list[str] = []

        # Title
        parts.append(f"# {report.title}")
        parts.append("")
        parts.append(f"*Research Question: {report.research_question}*")
        parts.append("")
        parts.append(
            f"*Generated on {report.generated_at.strftime('%B %d, %Y at %H:%M UTC')}*"
        )
        parts.append("")
        parts.append("---")
        parts.append("")

        # Table of Contents
        if report.config.include_table_of_contents:
            parts.append("## Table of Contents")
            parts.append("")
            sorted_sections = sorted(report.sections, key=lambda s: s.order)
            for i, section in enumerate(sorted_sections, 1):
                anchor = self._slugify(section.title)
                parts.append(f"{i}. [{section.title}](#{anchor})")
            if report.references:
                parts.append(f"{len(sorted_sections) + 1}. [References](#references)")
            parts.append("")
            parts.append("---")
            parts.append("")

        # Report statistics summary
        stats_line = (
            f"**Sources found:** {report.total_sources_found} · "
            f"**Sources used:** {report.total_sources_used} · "
            f"**Claims verified:** {report.total_claims_verified} · "
            f"**Generation time:** {report.generation_time_seconds:.1f}s"
        )
        parts.append(stats_line)
        parts.append("")
        parts.append("---")
        parts.append("")

        # Sections
        sorted_sections = sorted(report.sections, key=lambda s: s.order)
        for section in sorted_sections:
            parts.append(f"## {section.title}")
            parts.append("")
            parts.append(section.content)
            parts.append("")

        # References
        if report.references:
            parts.append("## References")
            parts.append("")
            sorted_refs = sorted(report.references, key=lambda r: r.index)
            for ref in sorted_refs:
                parts.append(ref.formatted)
                parts.append("")

        markdown = "\n".join(parts)
        self._log.info(
            "markdown_generation_complete",
            word_count=len(markdown.split()),
        )
        return markdown

    def generate_html(self, report: Report, markdown: str | None = None) -> str:
        """Generate a styled HTML document from the report.

        Parameters
        ----------
        report:
            The Report model.
        markdown:
            Optional pre-generated Markdown; if not provided, it is generated.

        Returns
        -------
        str
            Complete HTML document with embedded CSS.
        """
        self._log.info("html_generation_start", title=report.title)

        if markdown is None:
            markdown = self.generate_markdown(report)

        # Convert Markdown → HTML body
        html_body = markdown2.markdown(
            markdown,
            extras=[
                "fenced-code-blocks",
                "tables",
                "header-ids",
                "strike",
                "task_list",
                "footnotes",
                "cuddled-lists",
                "code-friendly",
            ],
        )

        # Wrap in a full HTML document with the title page
        generated_date = report.generated_at.strftime("%B %d, %Y")

        html_doc = f"""\
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="generator" content="Autonomous Research Agent">
    <meta name="author" content="Autonomous Research Agent">
    <title>{self._escape_html(report.title)}</title>
    <style>
{_REPORT_CSS}
    </style>
</head>
<body>
    <div class="title-block">
        <h1>{self._escape_html(report.title)}</h1>
        <div class="subtitle">{self._escape_html(report.research_question)}</div>
        <div class="meta">
            <span>Generated on {generated_date}</span>
            <span>Sources analyzed: {report.total_sources_found} · \
Sources cited: {report.total_sources_used}</span>
            <span>Claims verified: {report.total_claims_verified}</span>
        </div>
    </div>

    <div class="report-content">
{html_body}
    </div>

    <div class="report-stats">
        <p>This report was generated by the Autonomous Research Agent in \
{report.generation_time_seconds:.1f} seconds.</p>
        <p>{report.total_sources_found} sources discovered · \
{report.total_sources_used} sources cited · \
{report.total_claims_verified} claims cross-verified.</p>
    </div>
</body>
</html>
"""
        self._log.info("html_generation_complete")
        return html_doc

    async def generate_pdf(
        self,
        report: Report,
        html: str | None = None,
        output_path: str | Path | None = None,
    ) -> Path:
        """Generate a PDF from the report using WeasyPrint.

        Parameters
        ----------
        report:
            The Report model.
        html:
            Optional pre-generated HTML; if not provided, it is generated.
        output_path:
            Custom output path; defaults to ``<reports_dir>/<slug>.pdf``.

        Returns
        -------
        Path
            Absolute path to the generated PDF file.
        """
        self._log.info("pdf_generation_start", title=report.title)

        if html is None:
            html = self.generate_html(report)

        if output_path is None:
            self._output_dir.mkdir(parents=True, exist_ok=True)
            slug = self._slugify(report.title)
            timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
            output_path = self._output_dir / f"{slug}_{timestamp}.pdf"
        else:
            output_path = Path(output_path)
            output_path.parent.mkdir(parents=True, exist_ok=True)

        # WeasyPrint is CPU-heavy — run in a thread
        loop = asyncio.get_running_loop()
        await loop.run_in_executor(None, self._render_pdf, html, str(output_path))

        self._log.info("pdf_generation_complete", path=str(output_path))
        return output_path

    async def generate_all(
        self,
        report: Report,
        output_dir: str | Path | None = None,
    ) -> dict[str, str]:
        """Generate Markdown, HTML, and PDF outputs for the report.

        Parameters
        ----------
        report:
            The Report model.
        output_dir:
            Custom output directory; defaults to the configured reports dir.

        Returns
        -------
        dict[str, str]
            Mapping of format name to file path:
            ``{"markdown": "...", "html": "...", "pdf": "..."}``.
        """
        out = Path(output_dir) if output_dir else self._output_dir
        out.mkdir(parents=True, exist_ok=True)

        slug = self._slugify(report.title)
        timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")

        # 1. Markdown
        markdown = self.generate_markdown(report)
        md_path = out / f"{slug}_{timestamp}.md"

        # 2. HTML
        html = self.generate_html(report, markdown)
        html_path = out / f"{slug}_{timestamp}.html"

        # 3. PDF
        pdf_path = out / f"{slug}_{timestamp}.pdf"

        # Write files in parallel using threads
        loop = asyncio.get_running_loop()

        await asyncio.gather(
            loop.run_in_executor(None, self._write_text_file, str(md_path), markdown),
            loop.run_in_executor(None, self._write_text_file, str(html_path), html),
            loop.run_in_executor(None, self._render_pdf, html, str(pdf_path)),
        )

        # Update report model
        report.markdown_content = markdown
        report.pdf_path = str(pdf_path)

        self._log.info(
            "all_outputs_generated",
            markdown=str(md_path),
            html=str(html_path),
            pdf=str(pdf_path),
        )

        return {
            "markdown": str(md_path),
            "html": str(html_path),
            "pdf": str(pdf_path),
        }

    async def save_markdown(
        self, report: Report, output_path: str | Path | None = None
    ) -> Path:
        """Generate and save only the Markdown output.

        Parameters
        ----------
        report:
            The Report model.
        output_path:
            Custom output path.

        Returns
        -------
        Path
            Path to the saved Markdown file.
        """
        markdown = self.generate_markdown(report)

        if output_path is None:
            self._output_dir.mkdir(parents=True, exist_ok=True)
            slug = self._slugify(report.title)
            timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
            output_path = self._output_dir / f"{slug}_{timestamp}.md"
        else:
            output_path = Path(output_path)
            output_path.parent.mkdir(parents=True, exist_ok=True)

        loop = asyncio.get_running_loop()
        await loop.run_in_executor(
            None, self._write_text_file, str(output_path), markdown
        )

        report.markdown_content = markdown
        self._log.info("markdown_saved", path=str(output_path))
        return Path(output_path)

    # ── Internal helpers ────────────────────────────────────────

    @staticmethod
    def _render_pdf(html_string: str, output_path: str) -> None:
        """Render HTML to PDF using WeasyPrint (blocking, run in executor)."""
        from weasyprint import HTML

        html_doc = HTML(string=html_string)
        html_doc.write_pdf(output_path)

    @staticmethod
    def _write_text_file(path: str, content: str) -> None:
        """Write text content to a file (blocking, run in executor)."""
        Path(path).write_text(content, encoding="utf-8")

    @staticmethod
    def _slugify(text: str) -> str:
        """Convert text to a URL/filename-safe slug."""
        import re

        slug = text.lower().strip()
        slug = re.sub(r"[^\w\s-]", "", slug)
        slug = re.sub(r"[\s_]+", "-", slug)
        slug = re.sub(r"-{2,}", "-", slug)
        return slug[:80].strip("-")

    @staticmethod
    def _escape_html(text: str) -> str:
        """Escape HTML special characters."""
        return (
            text.replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace('"', "&quot;")
        )
